### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [GerryLarios/gerry-prompt#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by GerryLarios** [comment]
Hello @unixorn, I added a preview screenshot and a better description of this theme. 

Can you check one more time, please?

Thanks!
